### PR TITLE
Fix 79

### PR DESCRIPTION
**Pull request by nstuyvesant**
Fix for issue 79 and other corrections

### CODE REVIEW

**Comment by nstuyvesant** [comment]
@Maxl94 - can this be merged?

**Review by Maxl94 — APPROVED** [review]

**Comment by Maxl94** [comment]
Thanks for your work! I will create a new release Monday or Tuesday this week.

**Comment by nstuyvesant** [comment]
Thank you!

**Comment by nstuyvesant** [comment]
Thanks - would it make sense to publish a new version to npmjs?

**Comment by Maxl94** [comment]
> Thanks - would it make sense to publish a new version to npmjs?

I did that yesterday, sorry was a bit late.

**Comment by nstuyvesant** [comment]
Thanks!

**Pull request merged**
