### PR TITLE
Update to Angular 12

### PR DESCRIPTION
**Pull request by Hellysonrp**

### CODE REVIEW

**Comment by Maxl94** [comment]
Thanks for your PR - I don't think I'll have time for a review until next week.

**Comment by bsongis** [comment]
Works for me, thanks!

**Comment by SlasherZet** [comment]
> Thanks for your PR - I don't think I'll have time for a review until next week.

Any chance you will review it soon? It is incompatible with Angular Material 12 right now and it would be nice to be able to update to v12 in our projects!

**Comment by Maxl94** [comment]
I think I will do it tomorrow

**Review by Maxl94 — APPROVED** [review]

**Comment by Maxl94** [comment]
Released with version 0.7.0

**Pull request merged**
