### PR TITLE
feat!: updates to angular 17

### PR DESCRIPTION
**Pull request by Kurloc**
chore!: Update dependencies to support Angular 17
feat!: Move tsconfig to strict to mirror the default configuration in new angular projects more closely
fix!: Updated inner tsconfig for mat-multi-sort to provide a rootdir to override the inherited tsconfig's rootdir

### CODE REVIEW

**Comment by dzaunerOci** [comment]
any updates on this?

**Comment by AlexandruGiupana** [comment]
Any updates?

**Review by Maxl94 — APPROVED** [review]

**Comment by Maxl94** [comment]
@Kurloc thanks for you work. I just realized how less clue I have about typescript and angular in general after switching my filed of work. Would you like to get maintainer of this lib?

**Comment by Kurloc** [comment]
@Maxl94 Sorry I missed this notification. I wouldn't mind getting maintainer to help maintain the repo!

**Pull request merged**
